### ISSUE TITLE
Selenium tests are failing

### ISSUE THREAD

**Issue by noisecapella** [openedx/xblock-utils#47]
From the logs here: https://travis-ci.org/edx/xblock-utils/jobs/312058687
There are a bunch of exceptions like these:

    Traceback (most recent call last):
      File "/home/travis/build/edx/xblock-utils/xblockutils/base_test.py", line 44, in setUp
        super(SeleniumXBlockTest, self).setUp()
      File "/home/travis/build/edx/xblock-utils/.tox/django18/src/xblock-sdk/workbench/test/selenium_test.py", line 18, in setUp
        super(SeleniumTest, self).setUp()
      File "/home/travis/build/edx/xblock-utils/.tox/django18/lib/python2.7/site-packages/bok_choy/web_app_test.py", line 125, in setUp
        self.driver.set_window_position(0, 0)
      File "/home/travis/build/edx/xblock-utils/.tox/django18/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1010, in set_window_position
        return self.set_window_rect(x=int(x), y=int(y))
      File "/home/travis/build/edx/xblock-utils/.tox/django18/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1061, in set_window_rect
        "height": height})['value']
      File "/home/travis/build/edx/xblock-utils/.tox/django18/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
        self.error_handler.check_response(response)
      File "/home/travis/build/edx/xblock-utils/.tox/django18/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
        raise exception_class(message, screen, stacktrace)
    WebDriverException: Message: POST /session/0474914b-e6a3-44f3-b2f2-e9f9e59a30a0/window/rect did not match a known command

I fixed it locally by pinning `selenium==3.6`, but I haven't submitted a PR since I'm not sure how it should be fixed upstream.

**Comment by feanil** [comment]
Closing old issue before archiving this repo.
